apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9094
          name: kafka-external
        - containerPort: 9093
          name: kafka-controller
        command: ["/bin/sh"]
        args: ["-c", "KAFKA_NODE_ID=${POD_NAME##*-} KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:3000${POD_NAME##*-},PLAINTEXT://$(POD_NAME).kafka.default.svc:9092 /__cacert_entrypoint.sh /etc/kafka/docker/run"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_PROCESS_ROLES
          value: 'broker,controller'
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: '0@kafkacon-0:9093,1@kafkacon-1:9093,2@kafkacon-2:9093'
        - name: KAFKA_LISTENERS
          value: 'PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:9094'
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: 'PLAINTEXT'
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: 'CONTROLLER'
        - name: CLUSTER_ID
          value: '4L6g3nShT-eMCtK--X86sw'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: '0'
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: '1'
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_LOG_DIRS
          value: '/tmp/kraft-combined-logs'
