apiVersion: v1
kind: Service
metadata:
  name: kafka-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
  ports:
  - port: 9092
    nodePort: 30000
    protocol: TCP

  