apiVersion: v1
kind: Service
metadata:
  name: kafka-2
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
  ports:
  - port: 9094
    nodePort: 30002
    protocol: TCP

  